### ISSUE TITLE
Seeing red for contract size less than 24.576kb

### ISSUE THREAD

**Issue by pandichef** [ItsNickBarry/hardhat-contract-sizer#10]
`hardhat-contract-sizer` is telling me is that my contract is 24.1kb and is producing the warning message:  
`Warning: 1 contracts exceed the size limit for mainnet deployment.`

My understanding is that contracts can be as much as 24.675kb.

Is this a bug in `hardhat-contract-sizer` or is there some other legitimate reason I'm seeing `Warning: 1 contracts exceed the size limit for mainnet deployment.` ?

**Comment by ItsNickBarry** [comment]
Tentatively reported in #3.

> My understanding is that contracts can be as much as 24.675kb.
Source?

> Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.

**Comment by pandichef** [comment]
Apologies.  I meant 24.576kb above.  In any case, I'm getting an error at 24.1kb.

**Comment by ItsNickBarry** [comment]
Looks like the output is in KiB vs KB.  I will update.

**Comment by ItsNickBarry** [comment]
Fixed in `2.1.1`.
