### ISSUE TITLE
Display contract sizes in KiB rather than KB

### ISSUE THREAD

**Issue by RyanRHall** [ItsNickBarry/hardhat-contract-sizer#19]
[Contract size limit is 24 KB](https://eips.ethereum.org/EIPS/eip-170), or 24576 bytes. The current implementation divides contract size by 1000, rather than 1024, giving a slightly different impression of what the actual contract size is.

**Comment by ItsNickBarry** [comment]
24576 bytes is equal to 24 KiB or 24.576 KB.  This plugin displays data in KB.

However, I didn't realize until now that the limit in KiB is exactly 24, which is more convenient.  I may have realized this in the past, but the implementation had some issues and was changed: https://github.com/ItsNickBarry/hardhat-contract-sizer/commit/779d4c45bf7134a8fa5adfe540d4d458722a6ef1

I will look into what went wrong with the previous KiB implementation, and likely revert to KiB output for an upcoming release.

**Comment by RyanRHall** [comment]
Thank you for the clarification and consideration @ItsNickBarry

**Comment by ItsNickBarry** [comment]
Published in version `2.6.1`.
