### ISSUE TITLE
Support EIP3860 after Shanghai upgrade

### ISSUE THREAD

**Issue by rayeaster** [ItsNickBarry/hardhat-contract-sizer#32]
With [EIP 3860](https://eips.ethereum.org/EIPS/eip-3860#parameters), the contract size limit should be doubled from 24KB to 48KB?

https://github.com/ItsNickBarry/hardhat-contract-sizer/blob/95b202e75df3cc3fe309332bb8fa2062ad9a6ea2/tasks/size_contracts.js#L22
```diff
-  const SIZE_LIMIT = 24576
+ const SIZE_LIMIT = 24576 * 2
```

**Comment by ItsNickBarry** [comment]
I don't think so - that EIP appears to be adding a new, separate limit to initcode rather than deployed bytecode.  Perhaps the plugin could include initcode size in its report as a separate metric.
