### ISSUE TITLE
Validate initcode size

### ISSUE THREAD

**Issue by ItsNickBarry** [ItsNickBarry/hardhat-contract-sizer#33]
As mentioned in #32, there is now a limit on initialization code size in addition to deployed code size.  Initialization code size is also exposed in the compilation artifacts, so the plugin could (optionally?) also validate initialization code size.

See here: https://eips.ethereum.org/EIPS/eip-3860#parameters

**Comment by RyanRHall** [comment]
Personally I'd just throw it in a 3rd column. I don't think it's at the point of information overload yet. Happy to help contribute.

**Comment by RyanRHall** [comment]
Done!

https://github.com/ItsNickBarry/hardhat-contract-sizer/pull/36
