### ISSUE TITLE
Inconsistency between hardhat sizer & manual computation

### ISSUE THREAD

**Issue by OdysLam** [ItsNickBarry/hardhat-contract-sizer#4]
Hey, thanks for this cool tool :) 

I am having the following issue. Hardhat sizer shows that my contract is over the limit in color even though the size in number is ok. 

![image](https://user-images.githubusercontent.com/13405632/132174627-f9667332-7413-48fc-bfbc-0fbe528287d3.png)

Moreover, when I manually check the size of the contract, it's considerably larger.

```bash
cat artifacts/contracts/Loadout.sol/Loadout.json | jq -r '.deployedBytecode' | wc -c
   49863
```

Any ideas?

**Comment by ItsNickBarry** [comment]
Not really sure, but probably something to do with character encodings.  Does your calculation method always return 2x?

**Comment by ItsNickBarry** [comment]
Apparently `wc` output is a bit [complicated](https://unix.stackexchange.com/questions/51945/why-are-wc-m-and-wc-c-different), but it looks like it's calculating the ASCII bytes.  Bytecode is hex-encoded, so each character represents only half of a byte.
