### ISSUE TITLE
Feature Request: Breakdown contract size to each imported contract / lib size

### ISSUE THREAD

**Issue by sebastiantf** [ItsNickBarry/hardhat-contract-sizer#41]
Would be nice to have a feature where a contract's full size is broken down into steps that each shows the contract size of each imported contract. Would help to figure out which imported contract is contributing most to the final bytecode size

**Comment by ItsNickBarry** [comment]
That's not really possible, for two reasons:
1. If two contracts in an inheritance tree share similar code, the compilation optimizer will usually be able to combine them in such a way that the bytecode increases in a less-than-linear fashion.  The whole is smaller than the sum of its parts.
2. Inherited functions are often called by functions in the inheriting contract.  In these cases, which contract should those functions' bytecode be attributed to?

There's no real distinction between contracts that are linked by inheritance.  They're just one contract at that point.

**Comment by ItsNickBarry** [comment]
I suppose I could add a command like `hh size-contracts [CONTRACT_NAME]`, and output the size of just the specified contract and its imports.  But the output numbers would not be accurate within the context of the specified contract.  Not particularly useful.

**Comment by sebastiantf** [comment]
> If two contracts in an inheritance tree share similar code, the compilation optimizer will usually be able to combine them in such a way that the bytecode increases in a less-than-linear fashion.

Could you please explain this with an example? You're saying if contracts `ParentA::foo()` and `ParentB::bar()` has the same or similar implementation, `ChildC` would have separate, but optimized versions of both `foo()` & `bar()` both of which reuses the same code?

**Comment by ItsNickBarry** [comment]
I can't confirm, but the `--via-ir` compilation mode probably changes how this works even further.  Future changes to the base compiler might do the same.

**Comment by sebastiantf** [comment]
But what if the function names `Math::mul2()` and `Math2::mul2()` were different?

**Comment by ItsNickBarry** [comment]
> But what if the function names Math::mul2() and Math2::mul2() were different?

I made this change to confirm; same output.
