### ISSUE TITLE
Support for NPM?

### ISSUE THREAD

**Issue by grapevinegizmos** [ItsNickBarry/hardhat-contract-sizer#5]
If this works with NPM as well, could you add that to readme and how to install?

**Comment by ItsNickBarry** [comment]
Yes, this package works with NPM.  You probably want to run `npm install --save-dev hardhat-contract-sizer`.

The `yarn install` command is documented primarily as a means of providing the package name.  The actual command needed depends on the package manager in use by the end user, and it is not practical to document commands for every possible situation.

**Comment by grapevinegizmos** [comment]
thanks.  I'd just say that from the newcomer perspective it's non obvious that which package manager to use doesn't matter. It's not like NPM is an obscure long shot choice. Give us newbies and break ..it's hard enough to set up a new development environment without having to wonder whether i need to install Yarn to get your plugin.
