### ISSUE TITLE
Add feature to skip files

### ISSUE THREAD

**Issue by jchittoda** [ItsNickBarry/hardhat-contract-sizer#6]
Add a feature to skip the list of files to check for the contract size.

**Comment by ItsNickBarry** [comment]
I intend to create a unified interface for filtering files and incorporate it into several of my plugins, but it will not be ready for some time.  Do you need this feature urgently?  If so, I will accept a PR that incorporates the `only`/`except` options as defined in [hardhat-abi-exporter](https://github.com/ItsNickBarry/hardhat-abi-exporter).

**Comment by jchittoda** [comment]
Our contracts uses multiple solidity version, due to this we are bound to use the Hardhat and wanted to remove dependency from Truffle. We are using contract-size plugin which works with Truffle.

Its not urgent for us, as we found a workaround as of now. But in the future for sure we would need this feature.

**Comment by ItsNickBarry** [comment]
@jchittoda See `only` and `except` options released in version `2.2.0`.  Let me know if that interface works for you, or how it can be improved.  Behavior may change in a future release.
