### ISSUE TITLE
Add feature to fail the command when contract size exceeds 

### ISSUE THREAD

**Issue by jchittoda** [ItsNickBarry/hardhat-contract-sizer#7]
Fail the command when the contract size exceeds contract size limit.

This feature would be helpful in setting up CI job.

**Comment by ItsNickBarry** [comment]
Released in `2.1.0`.  See `strict` option.

**Comment by ItsNickBarry** [comment]
Potential issue remaining, see #8.

**Comment by jchittoda** [comment]
Thanks for adding `strict` option, but we have many test/mock contracts which are over the 24 bytes size. So we can use `strict` feature only with #6.
