### ISSUE TITLE
Disable `strict` option when `hardhat-coverage` is in use

### ISSUE THREAD

**Issue by ItsNickBarry** [ItsNickBarry/hardhat-contract-sizer#8]
The `hardhat-coverage` plugin greatly increases the size of contracts, and therefore cannot be used if the `strict` option is enabled.  Should check whether that plugin is running, or perhaps rely on the `allowUnlimitedContractSize` option.

**Comment by michaeljohnbennett** [comment]
ahhhhh... I think this is the cause of my issue... #9 

How best to get around this?

**Comment by ItsNickBarry** [comment]
Added a note to the readme.

**Comment by michaeljohnbennett** [comment]
I think the comment you added to the readme is an infinite loop 😄 

```whether to throw an error if any contracts exceed the size limit (may cause compatibility issues with hardhat-contract-sizer)```

Are you saying the strict flag causes compatibility issues with itself?

In the other ticket I have commented on the simple fix to get coverage to play nicely with a command line flag that flip/flops the `strict` flag on the config.

**Comment by ItsNickBarry** [comment]
Yes.

**Comment by gzliudan** [comment]
Can we pass strict as a parameter when call hardhat-contract-sizer, such as: `yarn run hardhat size-contracts --strict`

**Comment by arodundef** [comment]
Here I have the problem with the strict flag as true or false. The only difference is running coverage that stops the coverage as the contract size doesn't pass in the contract sizer. It works like a test. If a test fails, the coverage stops till you fix it.

I think the biggest issue is when running coverage. We get a different size than running the pure command or using `runOnCompile = true` and running test or compile.

Ex.:
```hh coverage```
![image](https://user-images.githubusercontent.com/90649201/146987382-14203603-9b21-4968-b1cd-45ea77ec9777.png)

```hh compile```
![image](https://user-images.githubusercontent.com/90649201/146987450-ba25d30f-a637-4f0d-981d-aeab13fd8178.png)

```hh size-contracts```
![image](https://user-images.githubusercontent.com/90649201/146987515-8e3faa02-b97a-4560-ba27-bc9b79e7476a.png)

**Comment by ItsNickBarry** [comment]
@gzliudan I will look into that feature, and might add in future.  Will also consider a PR.

@arodundef The coverage plugin modifies contract code and increases contract size.  It is fundamentally incompatible with `hardhat-contract-sizer`.

**Comment by arodundef** [comment]
> @gzliudan I will look into that feature, and might add in future. Will also consider a PR.
> 
> @arodundef The coverage plugin modifies contract code and increases contract size. It is fundamentally incompatible with `hardhat-contract-sizer`.

Got it. I'll trust in the other runners then. Thanks.

**Comment by ItsNickBarry** [comment]
released in `2.4.0`
